[versions]
agp = "9.0.1"
kotlin = "2.3.10"
ksp = "2.3.5" # KSP and Kotlin version compatibility

# Используется в Convention plugin-ах
min-sdk = "26"
target-sdk = "36"
compile-sdk = "36"
java = "17"
# =======================
# AndroidX
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
lifecycle-runtime-ktx = "2.10.0"

# Compose
compose-activity = "1.12.3"
compose-foundation = "1.10.2"
compose-ui = "1.10.2"
compose-material3 = "1.4.0"
javax-inject = "1"
# Retrofit
retrofit = "3.0.0"

# Tests
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockk = "1.14.9"

#Room
room = "2.8.4"

navigation = "2.9.5"

kotlin-serialization = "1.7.3"

# Hilt
hilt = "2.59.1"
hilt-navigation = "1.2.0"


# Google Servis
google-services = "4.4.4"
cloud-messaging = "25.0.1"
firebase-analytics = "23.2.0"
firebase-crashlytics = "20.0.5"
firebase-crashlytics-plugin = "3.0.7"
firebase-remote-config = "23.0.1"

tracer = "1.3.0"
firebaseMessaging = "24.0.0"

coroutines = "1.7.3"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
x-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

# Compose
x-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }


# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# Hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax-inject" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }


# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

# Internal convention plugins deps
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Google Services
firebase-cloud-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "cloud-messaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-remote-config = { module = "com.google.firebase:firebase-config", version.ref = "firebase-remote-config" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
# Tracer
tracer-platform = { module = "ru.ok.tracer:tracer-platform", version.ref = "tracer" }
tracer-crash-reporter = { module = "ru.ok.tracer:tracer-crash-report", version.ref = "tracer" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }


#Room
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }


[bundles]
compose-ui = ["compose-ui", "compose-ui-graphics", "compose-ui-tooling", "compose-ui-tooling-preview"]



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room-plugin = { id = "androidx.room", version.ref = "room" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics-plugin = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
tracer = { id = "ru.ok.tracer", version.ref = "tracer" }


# Project Internal convention plugins
app-android-application = { id = "app.android.application"}
app-android-library = { id = "app.android.library" }
app-compose = { id = "app.compose" }
app-room = { id = "app.room" }
app-hilt = { id = "app.hilt" }


